# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-17 21:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('global_settings', '0006_auto_20160116_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcastconfiguration',
            name='url_source',
            field=models.CharField(blank=True, default='', help_text='The source url where the recordings will be available after the upload. For example: "http://RadioCo.org/recordings/"', max_length=500, verbose_name='URL Source'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='about_footer',
            field=models.TextField(blank=True, default='', verbose_name='Footer'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='address',
            field=models.TextField(blank=True, default='', help_text='Can contain raw HTML.', verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='google_analytics_id',
            field=models.CharField(blank=True, default='', help_text='Example "UA-00000-0"', max_length=255, verbose_name='Google Analytics ID'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='more_about_us',
            field=models.TextField(blank=True, default='', verbose_name='More info'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='site_name',
            field=models.CharField(default='RadioCo', max_length=255, verbose_name='Site Name'),
        ),
    ]
