# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-21 15:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0005_auto_20170531_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='type',
            field=models.CharField(choices=[(b'L', 'live'), (b'B', 'broadcast'), (b'S', 'broadcast syndication'), (b'R', 'repetition')], max_length=1, verbose_name='type'),
        ),
    ]
