# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-21 17:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('programmes', '0014_auto_20171221_1735'),
        ('schedules', '0006_add_repetition_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='programme',
        ),
        migrations.AddField(
            model_name='schedule',
            name='slot',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='programmes.Slot', verbose_name='slot'),
            preserve_default=False,
        ),
    ]
