# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-22 16:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import datetime


def migrate_schedules_to_slots(apps, schema_editor):
    Programme = apps.get_model('programmes', 'Programme')
    Slot = apps.get_model('programmes', 'Slot')
    Schedule = apps.get_model('schedules', 'Schedule')
    for schedule in Schedule.objects.all():
        slot = Slot.objects.get(
            programme=schedule.programme,
            runtime=datetime.timedelta(minutes=schedule.programme._runtime))
        schedule.slot = slot
        schedule.save()


class Migration(migrations.Migration):

    dependencies = [
        ('programmes', '0014_create_slots'),
        ('schedules', '0006_add_repetition_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='slot',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='programmes.Slot', verbose_name='slot'),
            preserve_default=False,
        ),
        migrations.RunPython(migrate_schedules_to_slots),
        migrations.RemoveField(
            model_name='schedule',
            name='programme',
        ),
    ]
