# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-22 16:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import datetime


def migrate_runtime_to_slots(apps, schema_editor):
    Programme = apps.get_model('programmes', 'Programme')
    Slot = apps.get_model('programmes', 'Slot')
    for programme in Programme.objects.all():
        Slot.objects.get_or_create(
            programme=programme,
            runtime=datetime.timedelta(minutes=programme._runtime))


class Migration(migrations.Migration):

    dependencies = [
        ('programmes', '0013_programme_website'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('programme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programmes.Programme', verbose_name='programme')),
                ('runtime', models.DurationField(help_text='runtime in seconds', verbose_name='runtime')),
            ],
            options={
                'ordering': ['programme__name'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='episode',
            unique_together=set([]),
        ),
        migrations.RunPython(migrate_runtime_to_slots)
    ]
