# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-21 17:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('programmes', '0013_programme_website'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('runtime', models.DurationField(help_text='runtime in minutes', verbose_name='runtime')),
                ('programme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programmes.Programme', verbose_name='programme')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='episode',
            unique_together=set([]),
        ),
    ]
