# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-22 15:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programmes', '0014_auto_20171221_1735'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slot',
            options={'ordering': ['programme__name']},
        ),
        migrations.RemoveField(
            model_name='programme',
            name='_runtime',
        ),
        migrations.AlterField(
            model_name='slot',
            name='runtime',
            field=models.DurationField(help_text='runtime in seconds', verbose_name='runtime'),
        ),
    ]
