# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-25 22:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programmes', '0015_remove_programme_runtime'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='episode',
            unique_together=set([('season', 'number_in_season', 'programme')]),
        ),
    ]
