# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-22 21:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programmes', '0015_remove_programme_runtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='programme',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
