# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-17 21:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programmes', '0016_alter_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='role',
            field=models.CharField(choices=[('NO', 'Not specified'), ('PR', 'Presenter'), ('IN', 'Informer'), ('CO', 'Contributor')], default='NO', max_length=2, verbose_name='role'),
        ),
        migrations.AlterField(
            model_name='programme',
            name='category',
            field=models.CharField(blank=True, choices=[('Arts', 'Arts'), ('Business', 'Business'), ('Comedy', 'Comedy'), ('Education', 'Education'), ('Games & Hobbies', 'Games & Hobbies'), ('Government & Organizations', 'Government & Organizations'), ('Health', 'Health'), ('Kids & Family', 'Kids & Family'), ('Music', 'Music'), ('News & Politics', 'News & Politics'), ('Religion & Spirituality', 'Religion & Spirituality'), ('Science & Medicine', 'Science & Medicine'), ('Society & Culture', 'Society & Culture'), ('Sports & Recreation', 'Sports & Recreation'), ('Technology', 'Technology'), ('TV & Film', 'TV & Film')], max_length=50, null=True, verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='programme',
            name='language',
            field=models.CharField(choices=[('es', 'Spanish'), ('en', 'English'), ('gl', 'Galician')], default='es', max_length=7, verbose_name='language'),
        ),
        migrations.AlterField(
            model_name='programme',
            name='photo',
            field=models.ImageField(default='defaults/default-programme-photo.jpg', upload_to='photos/', verbose_name='photo'),
        ),
        migrations.AlterField(
            model_name='role',
            name='role',
            field=models.CharField(choices=[('NO', 'Not specified'), ('PR', 'Presenter'), ('IN', 'Informer'), ('CO', 'Contributor')], default='NO', max_length=2, verbose_name='role'),
        ),
    ]
